/*
 * Updated Date: 11/23/2014
 * Users: Jonathan Means,Karolina Reitz,
 * Users:Yuwen Huang, Paul Corter
 * 
 */
package fda.Graphics;

import fda.Containers.Beta;
import fda.Scrapers.BetaScraper;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.*;

public class FDA extends javax.swing.JFrame {
	private static final Logger logger = Logger.getLogger(FDA.class.getName());

    /** Creates new form Antenna */
    public FDA() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        displayficPanel = new javax.swing.JPanel();
        searchlinkLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        timerangeComboBox = new javax.swing.JComboBox();
        filterLabel = new javax.swing.JLabel();
        downloadPanel = new javax.swing.JPanel();
        chapterLabel = new javax.swing.JLabel();
        chapterTextField1 = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        chapterTextField2 = new javax.swing.JTextField();
        downloadlinkLabel = new javax.swing.JLabel();
        downloadTextField = new javax.swing.JTextField();
        DownloadButton = new javax.swing.JButton();
        folderButton = new javax.swing.JButton();
        totalchaptersTextField = new javax.swing.JTextField();
        totalchaptersButton = new javax.swing.JButton();
        folderSelecter = new javax.swing.JFileChooser();
        downloadLocationField = new javax.swing.JTextField();
        downloadLocationLabel = new javax.swing.JLabel();
        sortbetaPanel = new javax.swing.JPanel();
        betalinkLabel = new javax.swing.JLabel();
        sortBetaTextField = new javax.swing.JTextField();
        sortBetasearchButton = new javax.swing.JButton();

        betaScrollPane = new javax.swing.JScrollPane();

        betaTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fantastical Data Assistant");
        setResizable(false);
        displayficPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display the top 10 fics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        displayficPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        searchlinkLabel.setText("Fic URL:");

        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.setToolTipText("Search top 10 fics");
        searchButton.setMaximumSize(new java.awt.Dimension(85, 23));
        searchButton.setMinimumSize(new java.awt.Dimension(85, 23));
        searchButton.setPreferredSize(new java.awt.Dimension(85, 23));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        timerangeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Time Range:All", "Updated within 1 week", "Updated within 1 month", "Updated within 2 month"}));
        timerangeComboBox.setToolTipText("Time Range Options");
        timerangeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerangeComboBoxActionPerformed(evt);
            }
        });

        filterLabel.setText("Filter:");

        org.jdesktop.layout.GroupLayout displayficPanelLayout = new org.jdesktop.layout.GroupLayout(displayficPanel);
        displayficPanel.setLayout(displayficPanelLayout);
        displayficPanelLayout.setHorizontalGroup(
                displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(displayficPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(displayficPanelLayout.createSequentialGroup()
                                                .add(searchlinkLabel)
                                                .add(52, 52, 52)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(searchTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(displayficPanelLayout.createSequentialGroup()
                                                .add(filterLabel)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(timerangeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(40, 40, 40)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(searchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayficPanelLayout.setVerticalGroup(
                displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(displayficPanelLayout.createSequentialGroup()
                                .add(14, 14, 14)
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(searchlinkLabel)
                                        .add(searchButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(searchTextField))
                                .add(14, 14, 14)
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(filterLabel)
                                        .add(timerangeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(7, 7, 7))
        );

        searchlinkLabel.getAccessibleContext().setAccessibleName("searchlink");
        searchTextField.getAccessibleContext().setAccessibleName("searchTextfiled");

        downloadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Download", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chapterLabel.setText("Chapters:");
        chapterLabel.setToolTipText("");

        totalchaptersTextField.setEditable(false);

//        chapterTextField1.setEditable(false);
//        chapterTextField1.setText("1");

        toLabel.setText("To:");

//        chapterTextField2.setText("1");

        downloadlinkLabel.setText("Fic URL:");

        downloadTextField.setPreferredSize(new java.awt.Dimension(232, 20));
        downloadTextField.setSelectionEnd(45);
        downloadTextField.setSelectionStart(45);

        DownloadButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DownloadButton.setText("Download");
        DownloadButton.setToolTipText("Download fic to default C drive");
        DownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadButton1ActionPerformed(evt);
            }
        });

        folderButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        folderButton.setText("Location");
        folderButton.setToolTipText("Select Directory to Download files to");
        folderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderButton1ActionPerformed(evt);
            }
        });
        //totalchaptersLabel.setText("Total Chapters:");
        totalchaptersButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalchaptersButton.setText("Get total chapters");
        totalchaptersButton.setToolTipText("Display total chapters from the listed URL");
        totalchaptersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalchaptersButton1ActionPerformed(evt);
            }
        });

        folderSelecter.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        downloadLocationLabel.setText("Location:");
        downloadLocationLabel.setToolTipText("");

        org.jdesktop.layout.GroupLayout downloadPanelLayout = new org.jdesktop.layout.GroupLayout(downloadPanel);
        downloadPanel.setLayout(downloadPanelLayout);
        downloadPanelLayout.setHorizontalGroup(
                downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(downloadPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(downloadlinkLabel)
                                        .add(chapterLabel)
                                        .add(downloadLocationLabel))
                                .add(46, 46, 46)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(downloadTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(downloadLocationField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(downloadPanelLayout.createSequentialGroup()
                                                .add(chapterTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(toLabel)
                                                .add(18, 18, 18)
                                                .add(chapterTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(totalchaptersButton)
                                                .add(18, 18, 18)
                                                .add(totalchaptersTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(downloadPanelLayout.createSequentialGroup()
                                                .add(40, 40, 40)
                                                .add(DownloadButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, downloadPanelLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(folderButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        downloadPanelLayout.setVerticalGroup(
                downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(downloadPanelLayout.createSequentialGroup()
                                .add(16, 16, 16)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(downloadTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .add(DownloadButton))
                                .add(16, 16, 16)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(chapterLabel)
                                        .add(chapterTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(toLabel)
                                        .add(chapterTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(totalchaptersTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(totalchaptersButton))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(downloadLocationLabel)
                                        .add(downloadLocationField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(folderButton)))
                        .add(org.jdesktop.layout.GroupLayout.CENTER, downloadPanelLayout.createSequentialGroup()
                                .add(22, 22, 22)
                                .add(downloadlinkLabel)
                                .add(77, 77, 77))
        );

        chapterLabel.getAccessibleContext().setAccessibleName("chapters");
        chapterTextField1.getAccessibleContext().setAccessibleName("");
        toLabel.getAccessibleContext().setAccessibleName("To");
        downloadlinkLabel.getAccessibleContext().setAccessibleName("downloadlink");
        downloadTextField.getAccessibleContext().setAccessibleName("download");
        downloadTextField.getAccessibleContext().setAccessibleDescription("\\");
        downloadLocationLabel.getAccessibleContext().setAccessibleName("downloadLocation");

        sortbetaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "listings of beta readers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        sortbetaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        betalinkLabel.setText("Fic URL:");

        sortBetaTextField.setText("");
        sortBetaTextField.setSelectionEnd(45);
        sortBetaTextField.setSelectionStart(45);

        sortBetasearchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sortBetasearchButton.setText("Sort");
        sortBetasearchButton.setToolTipText("Sort beata reader");
        sortBetasearchButton.setFocusCycleRoot(true);
        sortBetasearchButton.setMaximumSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.setMinimumSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.setPreferredSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBetasearchButtonActionPerformed(evt);
            }
        });
        betaTextArea.setColumns(20);
        betaTextArea.setRows(5);
        betaScrollPane.setViewportView(betaTextArea);
        //betaScrollPane.setVisible(false);
        
        org.jdesktop.layout.GroupLayout sortbetaPanelLayout = new org.jdesktop.layout.GroupLayout(sortbetaPanel);
        sortbetaPanel.setLayout(sortbetaPanelLayout);
        sortbetaPanelLayout.setHorizontalGroup(
                sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(sortbetaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(betaScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 590, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(sortbetaPanelLayout.createSequentialGroup()
                                                .add(betalinkLabel)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(sortBetaTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(41, 41, 41)
                                                .add(sortBetasearchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        sortbetaPanelLayout.setVerticalGroup(
                sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(sortbetaPanelLayout.createSequentialGroup()
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(sortBetaTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(sortBetasearchButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(betalinkLabel))
                                .add(18, 18, 18)
                                .add(betaScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        betalinkLabel.getAccessibleContext().setAccessibleName("betalink");
        sortBetaTextField.getAccessibleContext().setAccessibleName("sortBeta");
        sortBetasearchButton.getAccessibleContext().setAccessibleDescription("Sort beta reader");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(downloadPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, displayficPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(sortbetaPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(displayficPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(downloadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(28, 28, 28)
                                .add(sortbetaPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayficPanel.getAccessibleContext().setAccessibleName("display10");
        sortbetaPanel.getAccessibleContext().setAccessibleName("sortBeta");

        pack();
    }// </editor-fold>
    public enum UrlType{FANDOM, FIC, BETA, UNKNOWN}
    public static final String BASE_URL = "https://www.fanfiction.net";
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        final String url = searchTextField.getText();
        if (UrlType.FANDOM== checkUrl(url))
        {
            //do search

            //this stores allows a translation from the date range selected to the number of days to search
            //ideally this would be refactored so that we only have to change the code in one place
            //if we want to alter the possible date ranges, but good enough for now
            int[] daySelection = {Integer.MAX_VALUE, 7, 30, 365 / 2};
            final int numDays = daySelection[timerangeComboBox.getSelectedIndex()];

                //This is necessary to keep the Progress Bar off the EDT
                //Otherwise it won't update
                SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            fanficJFrame frame = new fanficJFrame(url, numDays);
                            frame.setVisible(true);
                        } catch (IOException e) {
                            JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Dialog", JOptionPane.ERROR_MESSAGE);
                        }
                        return null;
                    }
                };
            worker.execute();

            System.out.println("and here do search");
        }
        else
        {
            //show error message
            String message = "The provided link does not appear to lead to a valid fandom.\n"
                    + "Please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void folderButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        int returnVal = folderSelecter.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION)
            downloadLocationField.setText(folderSelecter.getSelectedFile().toString());
    }

    private void totalchaptersButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (UrlType.FIC == checkUrl(downloadTextField.getText())) {
            try {
                Document doc1 = Jsoup.connect(downloadTextField.getText()).get();
                Elements Opts1 = doc1.select("option");
                String TCF = "" + (Opts1.size() / 2);
                totalchaptersTextField.setText(TCF);
            } catch (java.io.IOException ex) {
                java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                return;
            }
        }
        else
        {
            //show error message
            String message = "The download fic link is not recognized,\n"
                    + "please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void DownloadButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // // TODO download button:
        // validateURL validURl = new validateURL();
        //Verify URL and run download script if good
        if (UrlType.FIC == checkUrl(downloadTextField.getText())) {

            //Set Variables
            int chStart = 0;
            int chEnd = 0;
            String prevTitle = "";
            String nextTitle = "";
            String filenameTitle = "";

            //Set Jsoup Document
            org.jsoup.nodes.Document doc;

            //Separate the URL to change the chapter number for download
            String baseAddress = downloadTextField.getText().substring(0, downloadTextField.getText().lastIndexOf("/") - 1);
            baseAddress = baseAddress.substring(0, baseAddress.lastIndexOf("/")) + "/";

            //Pull the fic Name to act as a directory name and set the directory
            String ficName = downloadTextField.getText().substring(downloadTextField.getText().lastIndexOf("/") + 1);
            java.io.File dir = new java.io.File(downloadLocationField.getText() + java.io.File.separator + ficName);

            //Check to make sure required fields are not empty
            if (downloadLocationField.getText().equals("")) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Download Location Text Box is Empty", "FDA", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (chapterTextField1.getText().equals("")) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Beginning Chapters Text Box is Empty", "FDA", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (chapterTextField2.getText().equals("")) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Ending Chapters Text Box is Empty", "FDA", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            //Verify if directory exist, if not then create
            if (!dir.exists()) {
                try {
                    dir.mkdir();
                } catch (SecurityException se) {
                    java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, se);
                    return;  //Save directory couldn't be found or created, abort.
                }
            }

            // Verify Chapter Numbers
            try {
                chStart = Integer.parseInt(chapterTextField1.getText());
            } catch (java.lang.NumberFormatException ex) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Invalid Beginning Chapter Number", "FDA", JOptionPane.ERROR_MESSAGE);
                chapterTextField1.setText("");
                return;
            }
            try {
                chEnd = Integer.parseInt(chapterTextField2.getText());
            } catch (java.lang.NumberFormatException ex) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Invalid Ending Chapter Number", "FDA", JOptionPane.ERROR_MESSAGE);
                chapterTextField2.setText("");
                return;
            }
            if (chStart == 0 || chStart > chEnd) {
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame, "Beginning Chapter Number\ncan not be 0\n or greater then the Ending Chapter", "FDA", JOptionPane.ERROR_MESSAGE);
                chapterTextField1.setText("");
                return;
            }

            //Verify end Chapter number does not go beyond available chapters
            try {
                doc = Jsoup.connect(baseAddress + 1 + "/" + ficName).get();
                Elements Opts = doc.select("option"); //Pull the required elements(Chapters)
                //Verify that the ending chapter number is not greater than the total chapters available
                if (chStart > Opts.size() / 2) {
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                    JOptionPane.showMessageDialog(frame, "You can not select more than\n" + Opts.size() / 2 + " Chapters\nFor Chapter Start", "FDA", JOptionPane.ERROR_MESSAGE);
                    chapterTextField1.setText("");
                    return;
                }
                if (chEnd > Opts.size() / 2) {
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                    JOptionPane.showMessageDialog(frame, "You can not select more than\n" + Opts.size() / 2 + " Chapters\nFor Chapter End", "FDA", JOptionPane.ERROR_MESSAGE);
                    chapterTextField2.setText("");
                    return;
                }
            } catch (java.io.IOException ex) {
                java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            //Find out what files are already created
            int[] fileFound;
            try {
                Document doc1 = Jsoup.connect(downloadTextField.getText()).get();
                Elements Opts1 = doc1.select("option");
                String TCF = "" + (Opts1.size() / 2); //Get the total chapter count
                totalchaptersTextField.setText(TCF); //Label the total chapter count field.  A little redundant but here to make sure it populates
                fileFound = new int[(Opts1.size()/2)];
                for (int x = 0; x <=(Opts1.size() / 2) - 1; x++) {
                    fileFound[x] = 0; //Set to 0, meaning no file.
                }
                for (int checkFile = 0; checkFile <=(Opts1.size() / 2)-1; checkFile++) {
                    String checkTitle = Opts1.get(checkFile).text();
                    checkTitle = checkTitle.replace("'", "");
                    checkTitle = checkTitle.replace("?", "");
                    checkTitle = checkTitle.replace(". ", "_");
                    checkTitle = checkTitle.replace(" ", "_") + ".html";
                    checkTitle = (dir + java.io.File.separator + checkTitle);
                    java.io.File f = new java.io.File(checkTitle);
                    if (f.exists()) {
                        fileFound[checkFile] = 1;  //Set to 1 if file already exists
                    }
                }

            } catch (java.io.IOException ex) {
                java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                return;
            }

            //Check what files exists before and after the chapter numbers.
            //Change numbers if necessary
            if (chStart > 1) {
                for (int findStart = chStart - 1; findStart >= 1; findStart--) {
                    if (fileFound[findStart - 1] == 0) {
                        break;
                    } else {
                        chStart = findStart;
                    }
                }
            }
            for (int findEnd = chEnd + 1; findEnd <= fileFound.length; findEnd++) {
                if (fileFound[findEnd - 1] == 0) {
                    break;
                } else {
                    chEnd = findEnd;
                }
            }
            //Pull data with new chStart and chEnd
            for (int i = chStart; i <= chEnd; i++) {
                try {
                    doc = Jsoup.connect(baseAddress + i + "/" + ficName).get();
                    //Pull the required elements
                    Elements para = doc.select("p");
                    Elements ficTitle = doc.select("title");
                    Elements Opts = doc.select("option");

                    //Remove Authors Notes Supplemental
                    String strPara = "" + para;
                    int locPara = strPara.indexOf("Author's note, supplemental");
                    if (locPara == -1) {
                        locPara = strPara.indexOf("Author's Note, supplemental");
                    }
                    if (locPara > 0) {
                        strPara = strPara.substring(0, locPara);
                    }

                    String text = ficTitle + "</br>\n"; //Gives the web page the same title as the original.

                    //Get Titles and Filename
                    String pageTitle = Opts.get(i - 1).text();
                    pageTitle = "Chapter " + pageTitle.replace(".", ":");

                    if (i > 1) {
                        prevTitle = Opts.get(i - 2).text();
                        prevTitle = prevTitle.replace(". ", "_");
                        prevTitle = prevTitle.replace("?", "");
                        prevTitle = prevTitle.replace("'", "");
                        prevTitle = prevTitle.replace(" ", "_") + ".html";
                    }

                    filenameTitle = Opts.get(i - 1).text();
                    filenameTitle = filenameTitle.replace(". ", "_");
                    filenameTitle = filenameTitle.replace("?", "");
                    filenameTitle = filenameTitle.replace("'", "");
                    filenameTitle = filenameTitle.replace(" ", "_") + ".html";

                    nextTitle = Opts.get(i).text();
                    nextTitle = nextTitle.replace(". ", "_");
                    nextTitle = nextTitle.replace("?", "");
                    nextTitle = nextTitle.replace("'", "");
                    nextTitle = nextTitle.replace(" ", "_") + ".html";

                    //Setup web page
                    text = text + "<style type='text/css'>\n"
                            + "a:link {\n"
                            + "color: #00F;\n"
                            + "text-decoration: none;\n"
                            + "}\n"
                            + "a:visited {\n"
                            + "text-decoration: none;\n"
                            + "color: #F00;\n"
                            + "}\n"
                            + "a:hover {\n"
                            + "text-decoration: none;\n"
                            + "color: #0F0;\n"
                            + "}\n"
                            + "a:active {\n"
                            + "text-decoration: none;\n"
                            + "color: #006;\n"
                            + "}\n"
                            + "body {\n"
                            + "    margin-left: 50px;\n"
                            + "    margin-top: 25px;\n"
                            + "    margin-right: 50px;\n"
                            + "    margin-bottom: 25px;\n"
                            + "}\n"
                            + "</style>\n"
                            + "<body>\n"
                            + "<center><h3>" + pageTitle + "</h3></center>\n"
                            + strPara + "\n";
                    if (chStart == chEnd) {
                        text = text + "\n"; //No Links
                    } else if (i == 1 || i == chStart) {
                        text = text + "<center><a href='" + nextTitle + "'>" + Opts.get(i).text() + "</a></center>\n"; //Next Link
                    } else if (i > 1 && i > chStart && i < chEnd) {
                        text = text + "<center><a href='" + prevTitle + "'>" + Opts.get(i - 2).text() + "</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='" + nextTitle + "'>" + Opts.get(i).text() + "</a></center>\n"; //Previous and Next Links
                    } else if (i == chEnd) {
                        text = text + "<center><a href='" + prevTitle + "'>" + Opts.get(i - 2).text() + "</a></center>\n"; //Previous Link
                    }

                    text = text + "</br><center><a href='" + baseAddress + i + "/" + ficName + "' target=_blank>Original Web Page</a></center></br>\n"; //Link to original website
                    java.io.File chapter = new java.io.File(dir + java.io.File.separator + filenameTitle);

                    FileWriter oStream = new FileWriter(chapter);
                    oStream.write(text);
                    oStream.close();
                } catch (java.io.IOException ex) {
                    java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }

            //Inform that downloads are complete
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "Fan Fiction Downloads Complete", "FDA", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            //show error message
            String message = "The download fic link is not recognized,\n"
                    + "please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sortBetasearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
betaScrollPane.setVisible(false);
		
		// Retrieve the URL to download the beta readers from
		final String url = sortBetaTextField.getText();
		
		// Validate the URL
		if (UrlType.BETA == checkUrl(url)) {

			// This is necessary to keep the Progress Bar off the EDT
			// Otherwise it won't update
			SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
				@Override
				protected Void doInBackground() throws Exception {
					try {
						// Extract the beta readers
						List<Beta> betas = BetaScraper.extractBetas(url);
						StringBuffer buffer = new StringBuffer();
						
						// Loop through the betas and add them to the list in the GUI
						for (Beta beta : betas) {
							buffer.append(beta.getName() + " ("
									+ beta.getNumStories() + ") "
									+ beta.getBetaUrl() + "\n");
						}
						betaTextArea.setText(buffer.toString());
					} catch (IOException ioe) {
						logger.log(Level.SEVERE, "Error scraping betas from "
								+ url, ioe);
					}

					betaScrollPane.setVisible(true);
					return null;
				}
			};
			worker.execute();
		} else {
			// show error message
			String message = "\"The beta link is not recognized,\"\n"
					+ "please try again.";
			JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
					JOptionPane.ERROR_MESSAGE);
		}
    }

    private void timerangeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO filter display top 10 fics:
        // get the selected item:
        int selection;
        String selectedBook = (String) timerangeComboBox.getSelectedItem();
        if(timerangeComboBox.getSelectedIndex()==0) selection=100;
        else if (timerangeComboBox.getSelectedIndex()==1) selection=7;
        else if (timerangeComboBox.getSelectedIndex()==2) selection=30;
        else if (timerangeComboBox.getSelectedIndex()==3) selection=60;
        System.out.println("Filter: " + selectedBook);
    }
    public UrlType checkUrl(String url) {
        String ficString = BASE_URL + "/s/\\d+/\\d+/.+";
        String betaString = BASE_URL + "/betareaders/.+";
        String fandomString = BASE_URL + "/.+";
        //Test whether URL matches the fic pattern
        Pattern storyPattern = Pattern.compile(ficString);
        Matcher storyMatcher = storyPattern.matcher(url);
        if (storyMatcher.find()) {
            return UrlType.FIC;
        }
        //Test whether URL matches the beta listing pattern
        Pattern betaPattern = Pattern.compile(betaString);
        Matcher betaMatcher = betaPattern.matcher(url);
        if (betaMatcher.find()) { return UrlType.BETA; }
        //Test whether URL matches the fandom pattern
        Pattern fandomPattern = Pattern.compile(fandomString);
        Matcher fandomMatcher = fandomPattern.matcher(url);
        if (fandomMatcher.find()) { return UrlType.FANDOM; }
        return UrlType.UNKNOWN;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton DownloadButton;
    private javax.swing.JScrollPane betaScrollPane;
    private javax.swing.JTextArea betaTextArea;
    private javax.swing.JButton folderButton;
    private javax.swing.JLabel betalinkLabel;
    private javax.swing.JLabel chapterLabel;
    private javax.swing.JTextField chapterTextField1;
    private javax.swing.JTextField chapterTextField2;
    private javax.swing.JPanel displayficPanel;
    private javax.swing.JTextField downloadLocationField;
    private javax.swing.JLabel downloadLocationLabel;
    private javax.swing.JPanel downloadPanel;
    private javax.swing.JTextField downloadTextField;
    private javax.swing.JLabel downloadlinkLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JFileChooser folderSelecter;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel searchlinkLabel;
    private javax.swing.JTextField sortBetaTextField;
    private javax.swing.JButton sortBetasearchButton;
    private javax.swing.JPanel sortbetaPanel;
    private javax.swing.JComboBox timerangeComboBox;
    private javax.swing.JLabel toLabel;
    //private javax.swing.JLabel totalchaptersLabel;
    private javax.swing.JButton totalchaptersButton;
    private javax.swing.JTextField totalchaptersTextField;
    // End of variables declaration

}
