/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fda;


import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.io.IOException;
import java.util.Arrays;

public class fanficJFrame extends javax.swing.JFrame {

    /**
     * Creates new form fanficJFrame
     */
    public fanficJFrame(String url, int numDays) throws IOException {
        //for testing
        //delete this!
        numDays = 1;
        initComponents(url, numDays);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String url, int numDays) throws IOException {

        graphPanel = new javax.swing.JPanel();
        otherPanel = new javax.swing.JPanel();
        SummaryPanel = new javax.swing.JPanel();
        ratingLabel = new javax.swing.JLabel();
        chaptersLabel = new javax.swing.JLabel();
        wordsLabel = new javax.swing.JLabel();
        reviewsLabel = new javax.swing.JLabel();
        favoritesLabel = new javax.swing.JLabel();
        followsLabel = new javax.swing.JLabel();
        charactersLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        ratingTextField = new javax.swing.JTextField();
        chaptersTextField = new javax.swing.JTextField();
        wordsTextField = new javax.swing.JTextField();
        reviewsTextField = new javax.swing.JTextField();
        favoritesTextField = new javax.swing.JTextField();
        followsTextField = new javax.swing.JTextField();
        characterTextField = new javax.swing.JTextField();
        genreTextField = new javax.swing.JTextField();
        fanScrollPane = new javax.swing.JScrollPane();
        fanficList = new javax.swing.JList();

        //initialize required arrays of Fanfics
        Fanfic[] fics = FandomScraper.extractFics(url, numDays);
        int separatorIndex = Arrays.asList(fics).indexOf(null);
        final Fanfic[] topFics = new Fanfic[separatorIndex];
        System.arraycopy(fics, 0, topFics, 0, separatorIndex);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        otherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));

        javax.swing.GroupLayout otherPanelLayout = new javax.swing.GroupLayout(otherPanel);
        otherPanel.setLayout(otherPanelLayout);
        otherPanelLayout.setHorizontalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        otherPanelLayout.setVerticalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        SummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fic Summery"));

        ratingLabel.setText("Rating:");

        chaptersLabel.setText("Chapters");

        wordsLabel.setText("Words:");

        reviewsLabel.setText("Reviews:");

        favoritesLabel.setText("Favorites:");

        followsLabel.setText("Follows:");

        charactersLabel.setText("Characters:");

        genreLabel.setText("Genres:");

        ratingTextField.setText("");
        ratingTextField.setAutoscrolls(false);

        chaptersTextField.setText("");
        chaptersTextField.setAutoscrolls(false);

        wordsTextField.setText("");
        wordsTextField.setAutoscrolls(false);
        wordsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsTextFieldActionPerformed(evt);
            }
        });

        reviewsTextField.setText("");
        reviewsTextField.setAutoscrolls(false);
        reviewsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewsTextFieldActionPerformed(evt);
            }
        });

        favoritesTextField.setText("");
        favoritesTextField.setAutoscrolls(false);
        favoritesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritesTextFieldActionPerformed(evt);
            }
        });

        followsTextField.setText("");
        followsTextField.setAutoscrolls(false);
        followsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followsTextFieldActionPerformed(evt);
            }
        });

        characterTextField.setText("");
        characterTextField.setAutoscrolls(false);
        characterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterTextFieldActionPerformed(evt);
            }
        });

        genreTextField.setText("");
        genreTextField.setAutoscrolls(false);
        genreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paringTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SummaryPanelLayout = new javax.swing.GroupLayout(SummaryPanel);
        SummaryPanel.setLayout(SummaryPanelLayout);
        SummaryPanelLayout.setHorizontalGroup(
            SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SummaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingLabel)
                    .addComponent(chaptersLabel)
                    .addComponent(wordsLabel)
                    .addComponent(reviewsLabel)
                    .addComponent(favoritesLabel)
                    .addComponent(followsLabel)
                    .addComponent(charactersLabel)
                    .addComponent(genreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chaptersTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reviewsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoritesTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(followsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SummaryPanelLayout.setVerticalGroup(
            SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SummaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLabel)
                    .addComponent(ratingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chaptersLabel)
                    .addComponent(chaptersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordsLabel)
                    .addComponent(wordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reviewsLabel)
                    .addComponent(reviewsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favoritesLabel)
                    .addComponent(favoritesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followsLabel)
                    .addComponent(followsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charactersLabel)
                    .addComponent(characterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreLabel)
                    .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ratingLabel.getAccessibleContext().setAccessibleName("Rating");
        wordsLabel.getAccessibleContext().setAccessibleName("Words");
        favoritesLabel.getAccessibleContext().setAccessibleName("Favorites");
        followsLabel.getAccessibleContext().setAccessibleName("Follows");
        charactersLabel.getAccessibleContext().setAccessibleName("Characters");
        genreLabel.getAccessibleContext().setAccessibleName("Genres");

        fanScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Top Fics"));

        fanficList.setModel(new javax.swing.AbstractListModel<Fanfic>() {
            Fanfic[] fics = topFics;
            public int getSize() { return fics.length; }
            public Fanfic getElementAt(int i) { return fics[i]; }
        });
        System.out.println("Model set!");
        fanScrollPane.setViewportView(fanficList);
        fanficList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        fanficList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                Fanfic fic = (Fanfic) fanficList.getSelectedValue();
                ratingTextField.setText(fic.getRating());
                chaptersTextField.setText(Integer.toString(fic.getChapters()));
                wordsTextField.setText(Integer.toString(fic.getWords()));
                reviewsTextField.setText(Integer.toString(fic.getReviews()));
                favoritesTextField.setText(Integer.toString(fic.getFavorites()));
                followsTextField.setText(Integer.toString(fic.getFollows()));

                String charString = fic.getCharacters()[0];
                for (int i = 1; i < fic.getCharacters().length; ++i) {
                    if (fic.getCharacters()[i] != null) {
                        charString += ", " + fic.getCharacters()[i];
                    }
                }

                characterTextField.setText(charString);

                String genreString = fic.getGenres()[0];
                for (int i = 1; i < fic.getGenres().length; ++i) {
                    if (fic.getGenres()[i] != null) {
                        genreString += "\\" + fic.getGenres()[i];
                    }
                }

                genreTextField.setText(genreString);

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fanScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(otherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void reviewsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void wordsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void favoritesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void followsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void characterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void paringTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               


    // Variables declaration - do not modify                     
    private javax.swing.JPanel SummaryPanel;
    private javax.swing.JLabel chaptersLabel;
    private javax.swing.JTextField chaptersTextField;
    private javax.swing.JTextField characterTextField;
    private javax.swing.JLabel charactersLabel;
    private javax.swing.JScrollPane fanScrollPane;
    public static javax.swing.JList fanficList;
    private javax.swing.JLabel favoritesLabel;
    private javax.swing.JTextField favoritesTextField;
    private javax.swing.JLabel followsLabel;
    private javax.swing.JTextField followsTextField;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JPanel otherPanel;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JTextField ratingTextField;
    private javax.swing.JLabel reviewsLabel;
    private javax.swing.JTextField reviewsTextField;
    private javax.swing.JLabel wordsLabel;
    private javax.swing.JTextField wordsTextField;
    // End of variables declaration                   
}
