/*
 * GUI for displaying the results of a fandom search.
 * Authors: Yuwen Huang, Jonathan Means
 */
package fda;


import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.io.IOException;
import java.util.Arrays;

public class fanficJFrame extends javax.swing.JFrame {

    /**
     * Creates new form fanficJFrame
     */
    public fanficJFrame(String url, int numDays) throws IOException {
        initComponents(url, numDays);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String url, int numDays) throws IOException {

        graphPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphTextArea = new javax.swing.JTextArea();
        otherPanel = new javax.swing.JPanel();
        languageLabel = new javax.swing.JLabel();
        languageTextField = new javax.swing.JTextField();
        genresLabel = new javax.swing.JLabel();
        lotherTextField = new javax.swing.JTextField();
        wordCntLabel = new javax.swing.JLabel();
        wordCntTextField = new javax.swing.JTextField();
        otherLabel = new javax.swing.JLabel();
        genreTextField = new javax.swing.JTextField();
        popularityLabel = new javax.swing.JLabel();
        popularityTextField = new javax.swing.JTextField();
        writerButton = new javax.swing.JRadioButton();
        readerRadioButton = new javax.swing.JRadioButton();
        SummaryPanel = new javax.swing.JPanel();
        ratingLabel = new javax.swing.JLabel();
        chaptersLabel = new javax.swing.JLabel();
        wordsLabel = new javax.swing.JLabel();
        reviewsLabel = new javax.swing.JLabel();
        favoritesLabel = new javax.swing.JLabel();
        followsLabel = new javax.swing.JLabel();
        charactersLabel = new javax.swing.JLabel();
        pairingsLabel = new javax.swing.JLabel();
        ratingTextField = new javax.swing.JTextField();
        chaptersTextField = new javax.swing.JTextField();
        wordsTextField = new javax.swing.JTextField();
        reviewsTextField = new javax.swing.JTextField();
        favoritesTextField = new javax.swing.JTextField();
        followsTextField = new javax.swing.JTextField();
        characterTextField = new javax.swing.JTextField();
        paringTextField = new javax.swing.JTextField();
        summarytextArea = new javax.swing.JTextArea(500, 100);
        summarytextArea.setLineWrap(true);
        fanScrollPane = new javax.swing.JScrollPane();

        fanficList = new javax.swing.JList();

        //initialize required arrays of Fanfics
        Fanfic[] fics = FandomScraper.extractFics(url, numDays);
        int separatorIndex = Arrays.asList(fics).indexOf(null);
        final Fanfic[] topFics = new Fanfic[separatorIndex];
        System.arraycopy(fics, 0, topFics, 0, separatorIndex);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));

        graphTextArea.setColumns(20);
        graphTextArea.setLineWrap(true);
        graphTextArea.setRows(5);
        graphTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(graphTextArea);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
                graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(graphPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
                graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(graphPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );

        otherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));

        languageLabel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        languageLabel.setText("Language");

        genresLabel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        genresLabel.setText("Genres");

        lotherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotherTextFieldActionPerformed(evt);
            }
        });

        wordCntLabel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        wordCntLabel.setText("Word count");

        wordCntTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordCntTextFieldActionPerformed(evt);
            }
        });

        otherLabel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        otherLabel.setText("Other");

        genreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreTextFieldActionPerformed(evt);
            }
        });

        popularityLabel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        popularityLabel.setText("Popularity");

        popularityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularityTextFieldActionPerformed(evt);
            }
        });

        writerButton.setText("Writer_preferred");
        writerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writerButtonActionPerformed(evt);
            }
        });

        readerRadioButton.setText("Reader_preferred");
        readerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherPanelLayout = new javax.swing.GroupLayout(otherPanel);
        otherPanel.setLayout(otherPanelLayout);
        otherPanelLayout.setHorizontalGroup(
                otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherPanelLayout.createSequentialGroup()
                                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(languageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(languageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(genresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(wordCntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(otherPanelLayout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(wordCntLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(12, 12, 12))
                                        .addGroup(otherPanelLayout.createSequentialGroup()
                                                .addComponent(writerButton)
                                                .addGap(100, 100, 100)))
                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherPanelLayout.createSequentialGroup()
                                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(popularityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(otherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lotherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(readerRadioButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherPanelLayout.setVerticalGroup(
                otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(languageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(genresLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wordCntLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(popularityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(otherLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(popularityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lotherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(wordCntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(languageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(writerButton)
                                        .addComponent(readerRadioButton))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        SummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fic Summary"));

        ratingLabel.setText("Rating:");

        chaptersLabel.setText("Chapters");

        wordsLabel.setText("Words:");

        reviewsLabel.setText("Reviews:");

        favoritesLabel.setText("Favorites:");

        followsLabel.setText("Follows:");

        charactersLabel.setText("Characters:");

        pairingsLabel.setText("Pairings:");

        ratingTextField.setAutoscrolls(false);
        ratingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingTextFieldActionPerformed(evt);
            }
        });

        chaptersTextField.setAutoscrolls(false);

        wordsTextField.setAutoscrolls(false);
        wordsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsTextFieldActionPerformed(evt);
            }
        });

        reviewsTextField.setAutoscrolls(false);
        reviewsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewsTextFieldActionPerformed(evt);
            }
        });

        favoritesTextField.setAutoscrolls(false);
        favoritesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritesTextFieldActionPerformed(evt);
            }
        });

        followsTextField.setAutoscrolls(false);
        followsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followsTextFieldActionPerformed(evt);
            }
        });

        characterTextField.setAutoscrolls(false);
        characterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterTextFieldActionPerformed(evt);
            }
        });

        paringTextField.setAutoscrolls(false);
        paringTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paringTextFieldActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout SummaryPanelLayout = new javax.swing.GroupLayout(SummaryPanel);
        SummaryPanel.setLayout(SummaryPanelLayout);
        SummaryPanelLayout.setHorizontalGroup(
                SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SummaryPanelLayout.createSequentialGroup()
                                .addComponent(summarytextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ratingLabel)
                                        .addComponent(chaptersLabel)
                                        .addComponent(wordsLabel)
                                        .addComponent(reviewsLabel)
                                        .addComponent(favoritesLabel)
                                        .addComponent(followsLabel)
                                        .addComponent(charactersLabel)
                                        .addComponent(pairingsLabel))
                                .addGap(14, 14, 14)
                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(characterTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                        .addComponent(followsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(favoritesTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(reviewsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wordsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chaptersTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ratingTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(paringTextField))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SummaryPanelLayout.setVerticalGroup(
                SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SummaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SummaryPanelLayout.createSequentialGroup()
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ratingLabel)
                                                        .addComponent(ratingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(chaptersLabel)
                                                        .addComponent(chaptersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(wordsLabel)
                                                        .addComponent(wordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(13, 13, 13)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(reviewsLabel)
                                                        .addComponent(reviewsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(favoritesLabel)
                                                        .addComponent(favoritesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(followsLabel)
                                                        .addComponent(followsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(charactersLabel)
                                                        .addComponent(characterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(pairingsLabel)
                                                        .addComponent(paringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(summarytextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ratingLabel.getAccessibleContext().setAccessibleName("Rating");
        wordsLabel.getAccessibleContext().setAccessibleName("Words");
        favoritesLabel.getAccessibleContext().setAccessibleName("Favorites");
        followsLabel.getAccessibleContext().setAccessibleName("Follows");
        charactersLabel.getAccessibleContext().setAccessibleName("Characters");
        pairingsLabel.getAccessibleContext().setAccessibleName("Pairings");

        fanScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Fanfic Title by Author"));

        fanScrollPane.setViewportView(fanficList);
        fanScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Top Fics"));

        fanficList.setModel(new javax.swing.AbstractListModel<Fanfic>() {
            Fanfic[] fics = topFics;
            public int getSize() { return fics.length; }
            public Fanfic getElementAt(int i) { return fics[i]; }
        });

        fanScrollPane.setViewportView(fanficList);
        fanficList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        fanficList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                Fanfic fic = (Fanfic) fanficList.getSelectedValue();
                ratingTextField.setText(fic.getRating());
                chaptersTextField.setText(Integer.toString(fic.getChapters()));
                wordsTextField.setText(Integer.toString(fic.getWords()));
                reviewsTextField.setText(Integer.toString(fic.getReviews()));
                favoritesTextField.setText(Integer.toString(fic.getFavorites()));
                followsTextField.setText(Integer.toString(fic.getFollows()));
                summarytextArea.setText(fic.getSummary());

                String charString = fic.getCharacters()[0];
                for (int i = 1; i < fic.getCharacters().length; ++i) {
                    if (fic.getCharacters()[i] != null) {
                        charString += ", " + fic.getCharacters()[i];
                    }
                }

                characterTextField.setText(charString);

                String genreString = fic.getGenres()[0];
                for (int i = 1; i < fic.getGenres().length; ++i) {
                    if (fic.getGenres()[i] != null) {
                        genreString += "\\" + fic.getGenres()[i];
                    }
                }

                genreTextField.setText(genreString);

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(otherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fanScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                        .addComponent(SummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(fanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(otherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    private void reviewsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void wordsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void favoritesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void followsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void characterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void paringTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ratingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void readerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void genreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void wordCntTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void popularityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lotherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void writerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel SummaryPanel;
    private javax.swing.JLabel chaptersLabel;
    private javax.swing.JTextField chaptersTextField;
    private javax.swing.JTextField characterTextField;
    private javax.swing.JLabel charactersLabel;
    private javax.swing.JScrollPane fanScrollPane;
    public static javax.swing.JList fanficList;
    private javax.swing.JLabel favoritesLabel;
    private javax.swing.JTextField favoritesTextField;
    private javax.swing.JLabel followsLabel;
    private javax.swing.JTextField followsTextField;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JLabel genresLabel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JTextArea graphTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JTextField languageTextField;
    private javax.swing.JTextField lotherTextField;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JPanel otherPanel;
    private javax.swing.JLabel pairingsLabel;
    private javax.swing.JTextField paringTextField;
    private javax.swing.JLabel popularityLabel;
    private javax.swing.JTextField popularityTextField;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JTextField ratingTextField;
    private javax.swing.JRadioButton readerRadioButton;
    private javax.swing.JLabel reviewsLabel;
    private javax.swing.JTextField reviewsTextField;
    private javax.swing.JTextArea summarytextArea;
    private javax.swing.JLabel wordCntLabel;
    private javax.swing.JTextField wordCntTextField;
    private javax.swing.JLabel wordsLabel;
    private javax.swing.JTextField wordsTextField;
    private javax.swing.JRadioButton writerButton;
    // End of variables declaration                   
}
