
package fda;

import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;


public class FDA extends javax.swing.JFrame {

    public FDA() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        folderSelecter = new javax.swing.JFileChooser();
        displayficPanel = new javax.swing.JPanel();
        searchlinkLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        timerangeComboBox = new javax.swing.JComboBox();
        filterLabel = new javax.swing.JLabel();
        downloadPanel = new javax.swing.JPanel();
        chapterLabel = new javax.swing.JLabel();
        chapterTextField1 = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        chapterTextField2 = new javax.swing.JTextField();
        downloadlinkLabel = new javax.swing.JLabel();
        downloadTextField = new javax.swing.JTextField();
        DownloadButton = new javax.swing.JButton();
        downloadLocationLabel = new javax.swing.JLabel();
        downloadLocationField = new javax.swing.JTextField();
        folderButton = new javax.swing.JButton();
        sortbetaPanel = new javax.swing.JPanel();
        sortBetaTextField = new javax.swing.JTextField();
        betalinkLabel = new javax.swing.JLabel();
        sortBetasearchButton = new javax.swing.JButton();

        folderSelecter.setAccessory(folderButton);
        folderSelecter.setApproveButtonText("Save");
        folderSelecter.setApproveButtonToolTipText("");
        folderSelecter.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        folderSelecter.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fantastical Data Assistant");
        setResizable(false);

        displayficPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display the top 10 fics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        displayficPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        searchlinkLabel.setText("Fic URL:");

        searchTextField.setText("https://www.fanfiction.net/book/Harry-Potter/");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.setToolTipText("Search top 10 fics");
        searchButton.setMaximumSize(new java.awt.Dimension(85, 23));
        searchButton.setMinimumSize(new java.awt.Dimension(85, 23));
        searchButton.setPreferredSize(new java.awt.Dimension(85, 23));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        timerangeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Time Range:All", "Updated within 1 week", "Updated within 1 month", "Updated within 6 months"}));
        timerangeComboBox.setToolTipText("Time Range Options");
        timerangeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerangeComboBoxActionPerformed(evt);
            }
        });

        filterLabel.setText("Filter:");

        org.jdesktop.layout.GroupLayout displayficPanelLayout = new org.jdesktop.layout.GroupLayout(displayficPanel);
        displayficPanel.setLayout(displayficPanelLayout);
        displayficPanelLayout.setHorizontalGroup(
                displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(displayficPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(displayficPanelLayout.createSequentialGroup()
                                                .add(searchlinkLabel)
                                                .add(52, 52, 52)
                                                .add(searchTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(displayficPanelLayout.createSequentialGroup()
                                                .add(filterLabel)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(timerangeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(40, 40, 40)
                                .add(searchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        displayficPanelLayout.setVerticalGroup(
                displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(displayficPanelLayout.createSequentialGroup()
                                .add(14, 14, 14)
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(searchlinkLabel)
                                        .add(searchTextField)
                                        .add(searchButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(14, 14, 14)
                                .add(displayficPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(filterLabel)
                                        .add(timerangeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(7, 7, 7))
        );

        searchlinkLabel.getAccessibleContext().setAccessibleName("searchlink");
        searchTextField.getAccessibleContext().setAccessibleName("searchTextfiled");

        downloadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Download", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chapterLabel.setText("Chapters:");
        chapterLabel.setToolTipText("");

        chapterTextField1.setEditable(false);
        chapterTextField1.setText("1");

        toLabel.setText("To:");

        chapterTextField2.setText("1");

        downloadlinkLabel.setText("Fic URL:");

        downloadTextField.setText("https://www.fanfiction.net/s/9669819/1/The-Two-Year-Emperor ");
        downloadTextField.setPreferredSize(new java.awt.Dimension(232, 20));
        downloadTextField.setSelectionEnd(45);
        downloadTextField.setSelectionStart(45);
        downloadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadTextFieldActionPerformed(evt);
            }
        });

        DownloadButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DownloadButton.setText("Download");
        DownloadButton.setToolTipText("Download fic");
        DownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadButton1ActionPerformed(evt);
            }
        });

        downloadLocationLabel.setText("Location:");
        downloadLocationLabel.setToolTipText("");

        downloadLocationField.setToolTipText("");
        downloadLocationField.setPreferredSize(new java.awt.Dimension(232, 20));
        downloadLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadLocationFieldActionPerformed(evt);
            }
        });

        folderButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        folderButton.setText("Location");
        folderButton.setToolTipText("Download fic location");
        folderButton.setFocusPainted(false);
        folderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout downloadPanelLayout = new org.jdesktop.layout.GroupLayout(downloadPanel);
        downloadPanel.setLayout(downloadPanelLayout);
        downloadPanelLayout.setHorizontalGroup(
                downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(downloadPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(downloadlinkLabel)
                                        .add(chapterLabel)
                                        .add(downloadLocationLabel))
                                .add(46, 46, 46)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(downloadTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(downloadLocationField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, downloadPanelLayout.createSequentialGroup()
                                                .add(chapterTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(54, 54, 54)
                                                .add(toLabel)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(chapterTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(downloadPanelLayout.createSequentialGroup()
                                                .add(40, 40, 40)
                                                .add(DownloadButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, downloadPanelLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(folderButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        downloadPanelLayout.setVerticalGroup(
                downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(downloadPanelLayout.createSequentialGroup()
                                .add(16, 16, 16)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(downloadTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .add(DownloadButton))
                                .add(17, 17, 17)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(chapterLabel)
                                        .add(chapterTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(toLabel)
                                        .add(chapterTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                                .add(downloadPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(downloadLocationLabel)
                                        .add(downloadLocationField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(folderButton)))
                        .add(org.jdesktop.layout.GroupLayout.CENTER, downloadPanelLayout.createSequentialGroup()
                                .add(22, 22, 22)
                                .add(downloadlinkLabel)
                                .add(77, 77, 77))
        );

        chapterLabel.getAccessibleContext().setAccessibleName("chapters");
        chapterTextField1.getAccessibleContext().setAccessibleName("");
        toLabel.getAccessibleContext().setAccessibleName("To");
        downloadlinkLabel.getAccessibleContext().setAccessibleName("downloadlink");
        downloadTextField.getAccessibleContext().setAccessibleName("download");
        downloadTextField.getAccessibleContext().setAccessibleDescription("\\");
        downloadLocationLabel.getAccessibleContext().setAccessibleName("downloadLocation");

        sortbetaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "listings of beta readers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        sortbetaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sortBetaTextField.setText("https://www.fanfiction.net/betareaders/anime/Anima/");
        sortBetaTextField.setSelectionEnd(45);
        sortBetaTextField.setSelectionStart(45);
        sortBetaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBetaTextFieldActionPerformed(evt);
            }
        });

        betalinkLabel.setText("Fic URL:");

        sortBetasearchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sortBetasearchButton.setText("Sort");
        sortBetasearchButton.setToolTipText("Sort beata reader");
        sortBetasearchButton.setFocusCycleRoot(true);
        sortBetasearchButton.setMaximumSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.setMinimumSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.setPreferredSize(new java.awt.Dimension(85, 23));
        sortBetasearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBetasearchButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout sortbetaPanelLayout = new org.jdesktop.layout.GroupLayout(sortbetaPanel);
        sortbetaPanel.setLayout(sortbetaPanelLayout);
        sortbetaPanelLayout.setHorizontalGroup(
                sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(sortbetaPanelLayout.createSequentialGroup()
                                .add(betalinkLabel)
                                .add(55, 55, 55)
                                .add(sortBetaTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 374, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 47, Short.MAX_VALUE)
                                .add(sortBetasearchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        sortbetaPanelLayout.setVerticalGroup(
                sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(sortbetaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(sortbetaPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                        .add(sortBetaTextField)
                                        .add(sortBetasearchButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(betalinkLabel))
                                .addContainerGap())
        );

        sortBetaTextField.getAccessibleContext().setAccessibleName("sortBeta");
        betalinkLabel.getAccessibleContext().setAccessibleName("betalink");
        sortBetasearchButton.getAccessibleContext().setAccessibleDescription("Sort beta reader");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(14, 14, 14)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, displayficPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, downloadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, sortbetaPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(displayficPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(downloadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(sortbetaPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayficPanel.getAccessibleContext().setAccessibleName("display10");
        sortbetaPanel.getAccessibleContext().setAccessibleName("sortBeta");

        pack();
    }// </editor-fold>
    public enum UrlType{FANDOM, FIC, BETA, UNKNOWN}
    public static final String BASE_URL = "https://www.fanfiction.net";

    public int selection = Integer.MAX_VALUE;

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // validateURL validURl = new validateURL();
        String url = searchTextField.getText();
        if (UrlType.FANDOM== checkUrl(url))
        {
            fanficJFrame frame;
            try {
                frame = new fanficJFrame(url, selection);
                frame.setVisible(true);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        else
        {
            //show error message
            String message = "\"The search fic link is not recognized,\"\n"
                    + "please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void DownloadButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // // TODO download button:
        // validateURL validURl = new validateURL();
        if (UrlType.FIC == checkUrl(downloadTextField.getText()))
        {
            //do search
            System.out.println("and here do download");
            org.jsoup.nodes.Document doc;
            //try {
            //doc = org.jsoup.Jsoup.connect(downloadTextField.getText()).get();
            //String text = doc.body().text();
            String ficName = downloadTextField.getText().substring(downloadTextField.getText().lastIndexOf("/")+1);
            java.io.File dir = new java.io.File(downloadLocationField.getText()+java.io.File.separator+ficName);
            System.out.println("Downloading to "+dir.getAbsolutePath());
            if (!dir.exists()) {
                try {
                    dir.mkdir();
                } catch (SecurityException se) {
                    java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, se);
                    return;  //Save directory couldn't be found or created, abort.
                }
            }
            int chStart = Integer.parseInt(chapterTextField1.getText());
            int chEnd = Integer.parseInt(chapterTextField2.getText());
            String baseAddress = downloadTextField.getText().substring(0,downloadTextField.getText().lastIndexOf("/")-1);
            baseAddress = baseAddress.substring(0,baseAddress.lastIndexOf("/")) + "/";
            System.out.println("Base fanfic address "+baseAddress);
            for (int i=chStart; i<=chEnd; i++) {
                try {
                    doc = org.jsoup.Jsoup.connect(baseAddress + i + "/" + ficName).get();
                    String text = doc.body().text();
                    java.io.File chapter = new java.io.File(dir+java.io.File.separator+i+"_"+ficName+".html");
                    FileWriter oStream = new FileWriter(chapter);
                    oStream.write(text);
                    oStream.close();
                } catch (java.io.IOException ex) {
                    java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }

            //} catch (java.io.IOException ex) {
            //    java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            //}

        }
        else
        {
            //show error message
            String message = "\"The download fic link is not recognized,\"\n"
                    + "please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sortBetasearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // // TODO sort beta reader button:
        // validateURL validURl = new validateURL();
        if (UrlType.BETA == checkUrl(sortBetaTextField.getText()))
        {
            //do sort beta
            System.out.println("and here do sorting");
        }
        else
        {
            //show error message
            String message = "\"The beta link is not recognized,\"\n"
                    + "please try again.";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void downloadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void sortBetaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void timerangeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO filter display top 10 fics:
        // get the selected item:
        String selectedBook = (String) timerangeComboBox.getSelectedItem();
        if(timerangeComboBox.getSelectedIndex()==0) selection=Integer.MAX_VALUE; //If it's the max value, it will never actually
                                                     //get used. This is a simple approximation that will yield the right thing
                                                     //without having to recalculate how long the site's been around each time.
        else if (timerangeComboBox.getSelectedIndex()==1) selection=7;
        else if (timerangeComboBox.getSelectedIndex()==2) selection=30;
        else if (timerangeComboBox.getSelectedIndex()==3) selection=365 / 2;
        System.out.println("Filter: " + selectedBook);
    }

    private void downloadLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void folderButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int returnVal = folderSelecter.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION)
            downloadLocationField.setText(folderSelecter.getSelectedFile().toString());

    }
    public UrlType checkUrl(String url) {
        String ficString = BASE_URL + "/s/\\d+/\\d+/.+";
        String betaString = BASE_URL + "/betareaders/.+";
        String fandomString = BASE_URL + "/.+";
        //Test whether URL matches the fic pattern
        Pattern storyPattern = Pattern.compile(ficString);
        Matcher storyMatcher = storyPattern.matcher(url);
        if (storyMatcher.find()) {
            return UrlType.FIC;
        }
        //Test whether URL matches the beta listing pattern
        Pattern betaPattern = Pattern.compile(betaString);
        Matcher betaMatcher = betaPattern.matcher(url);
        if (betaMatcher.find()) { return UrlType.BETA; }
        //Test whether URL matches the fandom pattern
        Pattern fandomPattern = Pattern.compile(fandomString);
        Matcher fandomMatcher = fandomPattern.matcher(url);
        if (fandomMatcher.find()) { return UrlType.FANDOM; }
        return UrlType.UNKNOWN;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton DownloadButton;
    private javax.swing.JLabel betalinkLabel;
    private javax.swing.JLabel chapterLabel;
    private javax.swing.JTextField chapterTextField1;
    private javax.swing.JTextField chapterTextField2;
    private javax.swing.JPanel displayficPanel;
    private javax.swing.JTextField downloadLocationField;
    private javax.swing.JLabel downloadLocationLabel;
    private javax.swing.JPanel downloadPanel;
    private javax.swing.JTextField downloadTextField;
    private javax.swing.JLabel downloadlinkLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton folderButton;
    private javax.swing.JFileChooser folderSelecter;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel searchlinkLabel;
    private javax.swing.JTextField sortBetaTextField;
    private javax.swing.JButton sortBetasearchButton;
    private javax.swing.JPanel sortbetaPanel;
    private javax.swing.JComboBox timerangeComboBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration                   

}
